### ISSUE TITLE
Zaman girilebilmeli

### ISSUE THREAD

**Issue by b-yaz** [antoniormrzz/cikabilirmiyim#1]
Uygulama guzel düşünülmüş. Bir tarih girilip o tarihte de yasak durumunun ne oldugu onceden gorulebilirse guzel olacak.

**Comment by antoniormrzz** [comment]
Tabi, zamanım varsa eklerim, fikrini paylaştığın için teşekkür ederim 🙏

**Comment by antoniormrzz** [comment]
eklendi, kapatiyorum.

**Comment by b-yaz** [comment]
teşekkürler
