### ISSUE TITLE
saat kontrolü hatası hk.

### ISSUE THREAD

**Issue by malisasmaz** [antoniormrzz/cikabilirmiyim#2]
Merhaba,

Öncelikle güzel proje için tebrikler.
saat 20:03 ü seçtiğimde 21 den sonra çıkamazsın uyarısı veriyor. Ekran görüntüsünü ekliyorum.
![image](https://user-images.githubusercontent.com/5444250/100876464-7797dc80-34b8-11eb-9031-b75588d46cf1.png)

**Comment by antoniormrzz** [comment]
Teşekkür ederim, düzeltildi.
